
openapi: "3.0.1"
servers:
  - url: http://localhost:8080
    description: Local server
info:
  title: JobMailer API
  version: 1.0.0
  description: JobMailer API

paths:
    /healthcheck:
      $ref: './shared/healthcheck/healthcheck.yaml'
    /mail/status:
      $ref: "./mail/mailstatus.yaml"